### ISSUE TITLE
amberol binary is huge

### ISSUE THREAD

**Issue by soumyaDghosh** [alexmurray/amberol-snap#7]
The `amberol` executable in flatpak sizes just 2.0mb where as the snap one sizes atleast 100mb if not more. I have been digging into that. But, is there really something we are missing?

**Comment by alexmurray** [comment]
I suspect the flatpak runtime includes more of the required dependencies than the core22 base snap or gnome-42-2204 content snap and so the flatpak of amberol can be a lot smaller, whereas for the snap we need to include those dependencies directly in the amberol snap itself.

**Comment by soumyaDghosh** [comment]
But, that should not aftect the binary file itself? I don't about how rust work though.

**Comment by alexmurray** [comment]
I am also not sure about how rust binaries work. Leaving this open for now.

**Comment by alexmurray** [comment]
The changes in https://github.com/alexmurray/amberol-snap/commit/6d3dc4c8428325c048fe6a20b4d49bbca0602e8b now reduce the amberol binary  itself to just 20MB.

**Comment by soumyaDghosh** [comment]
Yet, I think, we should work on a gstreamer content snap.. It'd be just better to keep these separated. And that way also we can have latest version of gstreamer.

BTW, as I have said in the PR, this snap can't be updated to the latest version of the upstream, `0.10.2`

**Comment by alexmurray** [comment]
Yes I am aware that it can't be updated to 0.10.2 - that is why it is still 0.10.1 - we need a newer version of libadwaita than the one in Ubuntu 22.04

**Comment by soumyaDghosh** [comment]
Actually, the gnome-sdk have it, the `gnome` extension previously we used. But, I think, it specifically needed `libadwaita1.1`, that'
s in the Ubuntu repo. I don't know why the app didn't run with libadawita 1.3, that's why I removed it in my PR.

**Comment by soumyaDghosh** [comment]
Thanks a lot @alexmurray. That was awesome. Tried the latest edge `v0.10.3` and it's just 6Mb, that's crazy! From 180Mb to just 6Mb!!! Literally 1/30th. Thanks a lot for your hard effort. Thanks again!!!!! Closing this issue.
